// Mocks generated by Mockito 5.4.6 from annotations
// in doc_ledger/test/core/cloud/integration/backup_lifecycle_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:doc_ledger/core/cloud/services/google_drive_service.dart'
    as _i4;
import 'package:doc_ledger/core/data/models/data_models.dart' as _i9;
import 'package:doc_ledger/core/data/services/database_service.dart' as _i10;
import 'package:doc_ledger/core/encryption/models/encryption_models.dart'
    as _i3;
import 'package:doc_ledger/core/encryption/services/encryption_service.dart'
    as _i11;
import 'package:doc_ledger/core/sync/models/sync_models.dart' as _i2;
import 'package:doc_ledger/core/sync/services/sync_service.dart' as _i8;
import 'package:google_sign_in/google_sign_in.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSyncState_0 extends _i1.SmartFake implements _i2.SyncState {
  _FakeSyncState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncResult_1 extends _i1.SmartFake implements _i2.SyncResult {
  _FakeSyncResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEncryptedData_2 extends _i1.SmartFake implements _i3.EncryptedData {
  _FakeEncryptedData_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeviceInfo_3 extends _i1.SmartFake implements _i3.DeviceInfo {
  _FakeDeviceInfo_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GoogleDriveService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleDriveService extends _i1.Mock
    implements _i4.GoogleDriveService {
  MockGoogleDriveService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.AuthenticationState get authenticationState =>
      (super.noSuchMethod(
            Invocation.getter(#authenticationState),
            returnValue: _i4.AuthenticationState.notAuthenticated,
          )
          as _i4.AuthenticationState);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> authenticate({bool? forceAccountSelection = false}) =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, [], {
              #forceAccountSelection: forceAccountSelection,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> refreshTokens() =>
      (super.noSuchMethod(
            Invocation.method(#refreshTokens, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> handleAuthenticationFailure(Exception? error) =>
      (super.noSuchMethod(
            Invocation.method(#handleAuthenticationFailure, [error]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.GoogleSignInAccount>> getAvailableAccounts() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableAccounts, []),
            returnValue: _i5.Future<List<_i6.GoogleSignInAccount>>.value(
              <_i6.GoogleSignInAccount>[],
            ),
          )
          as _i5.Future<List<_i6.GoogleSignInAccount>>);

  @override
  _i5.Future<bool> switchAccount() =>
      (super.noSuchMethod(
            Invocation.method(#switchAccount, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> isAuthenticationValid() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticationValid, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<String> getBackupFolderId() =>
      (super.noSuchMethod(
            Invocation.method(#getBackupFolderId, []),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getBackupFolderId, []),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> uploadBackupFile(
    String? fileName,
    List<int>? encryptedData, {
    _i4.ProgressCallback? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadBackupFile,
              [fileName, encryptedData],
              {#onProgress: onProgress},
            ),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #uploadBackupFile,
                  [fileName, encryptedData],
                  {#onProgress: onProgress},
                ),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<List<int>> downloadBackupFile(
    String? fileId, {
    _i4.ProgressCallback? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadBackupFile,
              [fileId],
              {#onProgress: onProgress},
            ),
            returnValue: _i5.Future<List<int>>.value(<int>[]),
          )
          as _i5.Future<List<int>>);

  @override
  _i5.Future<List<_i4.BackupFileInfo>> listBackupFiles() =>
      (super.noSuchMethod(
            Invocation.method(#listBackupFiles, []),
            returnValue: _i5.Future<List<_i4.BackupFileInfo>>.value(
              <_i4.BackupFileInfo>[],
            ),
          )
          as _i5.Future<List<_i4.BackupFileInfo>>);

  @override
  _i5.Future<_i4.BackupFileInfo?> getLatestBackup() =>
      (super.noSuchMethod(
            Invocation.method(#getLatestBackup, []),
            returnValue: _i5.Future<_i4.BackupFileInfo?>.value(),
          )
          as _i5.Future<_i4.BackupFileInfo?>);

  @override
  _i5.Future<void> deleteOldBackups({
    int? maxDailyBackups = 30,
    int? maxMonthlyBackups = 12,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOldBackups, [], {
              #maxDailyBackups: maxDailyBackups,
              #maxMonthlyBackups: maxMonthlyBackups,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> validateBackupIntegrity(
    String? fileId,
    String? expectedChecksum,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#validateBackupIntegrity, [
              fileId,
              expectedChecksum,
            ]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> deleteFile(String? fileId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFile, [fileId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> updateBackupFile(
    String? fileId,
    String? fileName,
    List<int>? encryptedData, {
    _i4.ProgressCallback? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateBackupFile,
              [fileId, fileName, encryptedData],
              {#onProgress: onProgress},
            ),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #updateBackupFile,
                  [fileId, fileName, encryptedData],
                  {#onProgress: onProgress},
                ),
              ),
            ),
          )
          as _i5.Future<String>);
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i8.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i2.SyncState> get stateStream =>
      (super.noSuchMethod(
            Invocation.getter(#stateStream),
            returnValue: _i5.Stream<_i2.SyncState>.empty(),
          )
          as _i5.Stream<_i2.SyncState>);

  @override
  _i2.SyncState get currentState =>
      (super.noSuchMethod(
            Invocation.getter(#currentState),
            returnValue: _FakeSyncState_0(
              this,
              Invocation.getter(#currentState),
            ),
          )
          as _i2.SyncState);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i2.SyncResult> resolveConflicts(
    _i9.ResolutionStrategy? strategy,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resolveConflicts, [strategy]),
            returnValue: _i5.Future<_i2.SyncResult>.value(
              _FakeSyncResult_1(
                this,
                Invocation.method(#resolveConflicts, [strategy]),
              ),
            ),
          )
          as _i5.Future<_i2.SyncResult>);

  @override
  _i5.Future<_i2.SyncResult> resolveConflictsAutomatically() =>
      (super.noSuchMethod(
            Invocation.method(#resolveConflictsAutomatically, []),
            returnValue: _i5.Future<_i2.SyncResult>.value(
              _FakeSyncResult_1(
                this,
                Invocation.method(#resolveConflictsAutomatically, []),
              ),
            ),
          )
          as _i5.Future<_i2.SyncResult>);

  @override
  _i5.Future<List<_i9.SyncConflict>> getPendingConflicts() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingConflicts, []),
            returnValue: _i5.Future<List<_i9.SyncConflict>>.value(
              <_i9.SyncConflict>[],
            ),
          )
          as _i5.Future<List<_i9.SyncConflict>>);

  @override
  _i5.Future<_i2.SyncResult> resolveConflictManually(
    String? conflictId,
    Map<String, dynamic>? resolvedData, {
    String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #resolveConflictManually,
              [conflictId, resolvedData],
              {#notes: notes},
            ),
            returnValue: _i5.Future<_i2.SyncResult>.value(
              _FakeSyncResult_1(
                this,
                Invocation.method(
                  #resolveConflictManually,
                  [conflictId, resolvedData],
                  {#notes: notes},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.SyncResult>);

  @override
  _i5.Future<_i2.SyncResult> performFullSync() =>
      (super.noSuchMethod(
            Invocation.method(#performFullSync, []),
            returnValue: _i5.Future<_i2.SyncResult>.value(
              _FakeSyncResult_1(this, Invocation.method(#performFullSync, [])),
            ),
          )
          as _i5.Future<_i2.SyncResult>);

  @override
  _i5.Future<_i2.SyncResult> performIncrementalSync() =>
      (super.noSuchMethod(
            Invocation.method(#performIncrementalSync, []),
            returnValue: _i5.Future<_i2.SyncResult>.value(
              _FakeSyncResult_1(
                this,
                Invocation.method(#performIncrementalSync, []),
              ),
            ),
          )
          as _i5.Future<_i2.SyncResult>);

  @override
  _i5.Future<_i2.SyncResult> createBackup() =>
      (super.noSuchMethod(
            Invocation.method(#createBackup, []),
            returnValue: _i5.Future<_i2.SyncResult>.value(
              _FakeSyncResult_1(this, Invocation.method(#createBackup, [])),
            ),
          )
          as _i5.Future<_i2.SyncResult>);

  @override
  _i5.Future<_i2.SyncResult> restoreFromBackup(String? backupFileId) =>
      (super.noSuchMethod(
            Invocation.method(#restoreFromBackup, [backupFileId]),
            returnValue: _i5.Future<_i2.SyncResult>.value(
              _FakeSyncResult_1(
                this,
                Invocation.method(#restoreFromBackup, [backupFileId]),
              ),
            ),
          )
          as _i5.Future<_i2.SyncResult>);
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i10.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getChangedRecords(
    String? tableName,
    int? sinceTimestamp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getChangedRecords, [tableName, sinceTimestamp]),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<void> markRecordsSynced(
    String? tableName,
    List<String>? recordIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markRecordsSynced, [tableName, recordIds]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> applyRemoteChanges(
    String? tableName,
    List<Map<String, dynamic>>? records,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#applyRemoteChanges, [tableName, records]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i9.SyncConflict>> detectConflicts(
    String? tableName,
    List<Map<String, dynamic>>? remoteRecords,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#detectConflicts, [tableName, remoteRecords]),
            returnValue: _i5.Future<List<_i9.SyncConflict>>.value(
              <_i9.SyncConflict>[],
            ),
          )
          as _i5.Future<List<_i9.SyncConflict>>);

  @override
  _i5.Future<void> storeConflict(_i9.SyncConflict? conflict) =>
      (super.noSuchMethod(
            Invocation.method(#storeConflict, [conflict]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i9.SyncConflict>> getPendingConflicts() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingConflicts, []),
            returnValue: _i5.Future<List<_i9.SyncConflict>>.value(
              <_i9.SyncConflict>[],
            ),
          )
          as _i5.Future<List<_i9.SyncConflict>>);

  @override
  _i5.Future<void> resolveConflict(
    String? conflictId,
    _i9.ConflictResolution? resolution,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resolveConflict, [conflictId, resolution]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>> exportDatabaseSnapshot() =>
      (super.noSuchMethod(
            Invocation.method(#exportDatabaseSnapshot, []),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> importDatabaseSnapshot(Map<String, dynamic>? snapshot) =>
      (super.noSuchMethod(
            Invocation.method(#importDatabaseSnapshot, [snapshot]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateSyncMetadata(
    String? tableName, {
    int? lastSyncTimestamp,
    int? lastBackupTimestamp,
    int? pendingChangesCount,
    int? conflictCount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateSyncMetadata,
              [tableName],
              {
                #lastSyncTimestamp: lastSyncTimestamp,
                #lastBackupTimestamp: lastBackupTimestamp,
                #pendingChangesCount: pendingChangesCount,
                #conflictCount: conflictCount,
              },
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>?> getSyncMetadata(String? tableName) =>
      (super.noSuchMethod(
            Invocation.method(#getSyncMetadata, [tableName]),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<void> insertPatient(_i9.Patient? patient) =>
      (super.noSuchMethod(
            Invocation.method(#insertPatient, [patient]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updatePatient(_i9.Patient? patient) =>
      (super.noSuchMethod(
            Invocation.method(#updatePatient, [patient]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deletePatient(String? patientId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePatient, [patientId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i9.Patient?> getPatient(String? patientId) =>
      (super.noSuchMethod(
            Invocation.method(#getPatient, [patientId]),
            returnValue: _i5.Future<_i9.Patient?>.value(),
          )
          as _i5.Future<_i9.Patient?>);

  @override
  _i5.Future<List<_i9.Patient>> getAllPatients() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPatients, []),
            returnValue: _i5.Future<List<_i9.Patient>>.value(<_i9.Patient>[]),
          )
          as _i5.Future<List<_i9.Patient>>);

  @override
  _i5.Future<void> insertVisit(_i9.Visit? visit) =>
      (super.noSuchMethod(
            Invocation.method(#insertVisit, [visit]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateVisit(_i9.Visit? visit) =>
      (super.noSuchMethod(
            Invocation.method(#updateVisit, [visit]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteVisit(String? visitId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteVisit, [visitId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i9.Visit?> getVisit(String? visitId) =>
      (super.noSuchMethod(
            Invocation.method(#getVisit, [visitId]),
            returnValue: _i5.Future<_i9.Visit?>.value(),
          )
          as _i5.Future<_i9.Visit?>);

  @override
  _i5.Future<List<_i9.Visit>> getVisitsForPatient(String? patientId) =>
      (super.noSuchMethod(
            Invocation.method(#getVisitsForPatient, [patientId]),
            returnValue: _i5.Future<List<_i9.Visit>>.value(<_i9.Visit>[]),
          )
          as _i5.Future<List<_i9.Visit>>);

  @override
  _i5.Future<void> insertPayment(_i9.Payment? payment) =>
      (super.noSuchMethod(
            Invocation.method(#insertPayment, [payment]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updatePayment(_i9.Payment? payment) =>
      (super.noSuchMethod(
            Invocation.method(#updatePayment, [payment]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deletePayment(String? paymentId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePayment, [paymentId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i9.Payment?> getPayment(String? paymentId) =>
      (super.noSuchMethod(
            Invocation.method(#getPayment, [paymentId]),
            returnValue: _i5.Future<_i9.Payment?>.value(),
          )
          as _i5.Future<_i9.Payment?>);

  @override
  _i5.Future<List<_i9.Payment>> getPaymentsForPatient(String? patientId) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentsForPatient, [patientId]),
            returnValue: _i5.Future<List<_i9.Payment>>.value(<_i9.Payment>[]),
          )
          as _i5.Future<List<_i9.Payment>>);
}

/// A class which mocks [EncryptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEncryptionService extends _i1.Mock implements _i11.EncryptionService {
  MockEncryptionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.EncryptedData> encryptData(
    Map<String, dynamic>? data,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#encryptData, [data, password]),
            returnValue: _i5.Future<_i3.EncryptedData>.value(
              _FakeEncryptedData_2(
                this,
                Invocation.method(#encryptData, [data, password]),
              ),
            ),
          )
          as _i5.Future<_i3.EncryptedData>);

  @override
  _i5.Future<Map<String, dynamic>> decryptData(
    _i3.EncryptedData? encryptedData,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#decryptData, [encryptedData, password]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<String> generateDeviceId() =>
      (super.noSuchMethod(
            Invocation.method(#generateDeviceId, []),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#generateDeviceId, []),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> deriveEncryptionKey(
    String? clinicId,
    String? deviceSalt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deriveEncryptionKey, [clinicId, deviceSalt]),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#deriveEncryptionKey, [clinicId, deviceSalt]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<bool> validateDataIntegrity(
    List<int>? data,
    String? expectedChecksum,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#validateDataIntegrity, [data, expectedChecksum]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  String generateSalt() =>
      (super.noSuchMethod(
            Invocation.method(#generateSalt, []),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#generateSalt, []),
            ),
          )
          as String);

  @override
  _i5.Future<_i3.DeviceInfo> getDeviceInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceInfo, []),
            returnValue: _i5.Future<_i3.DeviceInfo>.value(
              _FakeDeviceInfo_3(this, Invocation.method(#getDeviceInfo, [])),
            ),
          )
          as _i5.Future<_i3.DeviceInfo>);
}
