// Mocks generated by Mockito 5.4.6 from annotations
// in doc_ledger/test/core/sync/services/data_integrity_handler_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:doc_ledger/core/cloud/services/google_drive_service.dart'
    as _i3;
import 'package:doc_ledger/core/encryption/models/encryption_models.dart'
    as _i2;
import 'package:doc_ledger/core/encryption/services/encryption_service.dart'
    as _i7;
import 'package:google_sign_in/google_sign_in.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEncryptedData_0 extends _i1.SmartFake implements _i2.EncryptedData {
  _FakeEncryptedData_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeviceInfo_1 extends _i1.SmartFake implements _i2.DeviceInfo {
  _FakeDeviceInfo_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GoogleDriveService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleDriveService extends _i1.Mock
    implements _i3.GoogleDriveService {
  MockGoogleDriveService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AuthenticationState get authenticationState =>
      (super.noSuchMethod(
            Invocation.getter(#authenticationState),
            returnValue: _i3.AuthenticationState.notAuthenticated,
          )
          as _i3.AuthenticationState);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> authenticate({bool? forceAccountSelection = false}) =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, [], {
              #forceAccountSelection: forceAccountSelection,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> refreshTokens() =>
      (super.noSuchMethod(
            Invocation.method(#refreshTokens, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> handleAuthenticationFailure(Exception? error) =>
      (super.noSuchMethod(
            Invocation.method(#handleAuthenticationFailure, [error]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.GoogleSignInAccount>> getAvailableAccounts() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableAccounts, []),
            returnValue: _i4.Future<List<_i5.GoogleSignInAccount>>.value(
              <_i5.GoogleSignInAccount>[],
            ),
          )
          as _i4.Future<List<_i5.GoogleSignInAccount>>);

  @override
  _i4.Future<bool> switchAccount() =>
      (super.noSuchMethod(
            Invocation.method(#switchAccount, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> isAuthenticationValid() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticationValid, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String> getBackupFolderId() =>
      (super.noSuchMethod(
            Invocation.method(#getBackupFolderId, []),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getBackupFolderId, []),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> uploadBackupFile(
    String? fileName,
    List<int>? encryptedData, {
    _i3.ProgressCallback? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadBackupFile,
              [fileName, encryptedData],
              {#onProgress: onProgress},
            ),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(
                  #uploadBackupFile,
                  [fileName, encryptedData],
                  {#onProgress: onProgress},
                ),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<List<int>> downloadBackupFile(
    String? fileId, {
    _i3.ProgressCallback? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadBackupFile,
              [fileId],
              {#onProgress: onProgress},
            ),
            returnValue: _i4.Future<List<int>>.value(<int>[]),
          )
          as _i4.Future<List<int>>);

  @override
  _i4.Future<List<_i3.BackupFileInfo>> listBackupFiles() =>
      (super.noSuchMethod(
            Invocation.method(#listBackupFiles, []),
            returnValue: _i4.Future<List<_i3.BackupFileInfo>>.value(
              <_i3.BackupFileInfo>[],
            ),
          )
          as _i4.Future<List<_i3.BackupFileInfo>>);

  @override
  _i4.Future<_i3.BackupFileInfo?> getLatestBackup() =>
      (super.noSuchMethod(
            Invocation.method(#getLatestBackup, []),
            returnValue: _i4.Future<_i3.BackupFileInfo?>.value(),
          )
          as _i4.Future<_i3.BackupFileInfo?>);

  @override
  _i4.Future<void> deleteOldBackups({
    int? maxDailyBackups = 30,
    int? maxMonthlyBackups = 12,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOldBackups, [], {
              #maxDailyBackups: maxDailyBackups,
              #maxMonthlyBackups: maxMonthlyBackups,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> validateBackupIntegrity(
    String? fileId,
    String? expectedChecksum,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#validateBackupIntegrity, [
              fileId,
              expectedChecksum,
            ]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> deleteFile(String? fileId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFile, [fileId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String> updateBackupFile(
    String? fileId,
    String? fileName,
    List<int>? encryptedData, {
    _i3.ProgressCallback? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateBackupFile,
              [fileId, fileName, encryptedData],
              {#onProgress: onProgress},
            ),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(
                  #updateBackupFile,
                  [fileId, fileName, encryptedData],
                  {#onProgress: onProgress},
                ),
              ),
            ),
          )
          as _i4.Future<String>);
}

/// A class which mocks [EncryptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEncryptionService extends _i1.Mock implements _i7.EncryptionService {
  MockEncryptionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.EncryptedData> encryptData(
    Map<String, dynamic>? data,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#encryptData, [data, password]),
            returnValue: _i4.Future<_i2.EncryptedData>.value(
              _FakeEncryptedData_0(
                this,
                Invocation.method(#encryptData, [data, password]),
              ),
            ),
          )
          as _i4.Future<_i2.EncryptedData>);

  @override
  _i4.Future<Map<String, dynamic>> decryptData(
    _i2.EncryptedData? encryptedData,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#decryptData, [encryptedData, password]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<String> generateDeviceId() =>
      (super.noSuchMethod(
            Invocation.method(#generateDeviceId, []),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#generateDeviceId, []),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> deriveEncryptionKey(
    String? clinicId,
    String? deviceSalt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deriveEncryptionKey, [clinicId, deviceSalt]),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#deriveEncryptionKey, [clinicId, deviceSalt]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<bool> validateDataIntegrity(
    List<int>? data,
    String? expectedChecksum,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#validateDataIntegrity, [data, expectedChecksum]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  String generateSalt() =>
      (super.noSuchMethod(
            Invocation.method(#generateSalt, []),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#generateSalt, []),
            ),
          )
          as String);

  @override
  _i4.Future<_i2.DeviceInfo> getDeviceInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceInfo, []),
            returnValue: _i4.Future<_i2.DeviceInfo>.value(
              _FakeDeviceInfo_1(this, Invocation.method(#getDeviceInfo, [])),
            ),
          )
          as _i4.Future<_i2.DeviceInfo>);
}
