// Mocks generated by Mockito 5.4.6 from annotations
// in doc_ledger/test/core/sync/services/sync_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:doc_ledger/core/cloud/services/google_drive_service.dart'
    as _i6;
import 'package:doc_ledger/core/data/models/data_models.dart' as _i5;
import 'package:doc_ledger/core/data/services/database_service.dart' as _i3;
import 'package:doc_ledger/core/encryption/models/encryption_models.dart'
    as _i2;
import 'package:doc_ledger/core/encryption/services/encryption_service.dart'
    as _i9;
import 'package:google_sign_in/google_sign_in.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEncryptedData_0 extends _i1.SmartFake implements _i2.EncryptedData {
  _FakeEncryptedData_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeviceInfo_1 extends _i1.SmartFake implements _i2.DeviceInfo {
  _FakeDeviceInfo_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i3.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getChangedRecords(
    String? tableName,
    int? sinceTimestamp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getChangedRecords, [tableName, sinceTimestamp]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> markRecordsSynced(
    String? tableName,
    List<String>? recordIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markRecordsSynced, [tableName, recordIds]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> applyRemoteChanges(
    String? tableName,
    List<Map<String, dynamic>>? records,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#applyRemoteChanges, [tableName, records]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.SyncConflict>> detectConflicts(
    String? tableName,
    List<Map<String, dynamic>>? remoteRecords,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#detectConflicts, [tableName, remoteRecords]),
            returnValue: _i4.Future<List<_i5.SyncConflict>>.value(
              <_i5.SyncConflict>[],
            ),
          )
          as _i4.Future<List<_i5.SyncConflict>>);

  @override
  _i4.Future<void> storeConflict(_i5.SyncConflict? conflict) =>
      (super.noSuchMethod(
            Invocation.method(#storeConflict, [conflict]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.SyncConflict>> getPendingConflicts() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingConflicts, []),
            returnValue: _i4.Future<List<_i5.SyncConflict>>.value(
              <_i5.SyncConflict>[],
            ),
          )
          as _i4.Future<List<_i5.SyncConflict>>);

  @override
  _i4.Future<void> resolveConflict(
    String? conflictId,
    _i5.ConflictResolution? resolution,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resolveConflict, [conflictId, resolution]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> exportDatabaseSnapshot() =>
      (super.noSuchMethod(
            Invocation.method(#exportDatabaseSnapshot, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> importDatabaseSnapshot(Map<String, dynamic>? snapshot) =>
      (super.noSuchMethod(
            Invocation.method(#importDatabaseSnapshot, [snapshot]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateSyncMetadata(
    String? tableName, {
    int? lastSyncTimestamp,
    int? lastBackupTimestamp,
    int? pendingChangesCount,
    int? conflictCount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateSyncMetadata,
              [tableName],
              {
                #lastSyncTimestamp: lastSyncTimestamp,
                #lastBackupTimestamp: lastBackupTimestamp,
                #pendingChangesCount: pendingChangesCount,
                #conflictCount: conflictCount,
              },
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> getSyncMetadata(String? tableName) =>
      (super.noSuchMethod(
            Invocation.method(#getSyncMetadata, [tableName]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> insertPatient(_i5.Patient? patient) =>
      (super.noSuchMethod(
            Invocation.method(#insertPatient, [patient]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updatePatient(_i5.Patient? patient) =>
      (super.noSuchMethod(
            Invocation.method(#updatePatient, [patient]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deletePatient(String? patientId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePatient, [patientId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.Patient?> getPatient(String? patientId) =>
      (super.noSuchMethod(
            Invocation.method(#getPatient, [patientId]),
            returnValue: _i4.Future<_i5.Patient?>.value(),
          )
          as _i4.Future<_i5.Patient?>);

  @override
  _i4.Future<List<_i5.Patient>> getAllPatients() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPatients, []),
            returnValue: _i4.Future<List<_i5.Patient>>.value(<_i5.Patient>[]),
          )
          as _i4.Future<List<_i5.Patient>>);

  @override
  _i4.Future<void> insertVisit(_i5.Visit? visit) =>
      (super.noSuchMethod(
            Invocation.method(#insertVisit, [visit]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateVisit(_i5.Visit? visit) =>
      (super.noSuchMethod(
            Invocation.method(#updateVisit, [visit]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteVisit(String? visitId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteVisit, [visitId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.Visit?> getVisit(String? visitId) =>
      (super.noSuchMethod(
            Invocation.method(#getVisit, [visitId]),
            returnValue: _i4.Future<_i5.Visit?>.value(),
          )
          as _i4.Future<_i5.Visit?>);

  @override
  _i4.Future<List<_i5.Visit>> getVisitsForPatient(String? patientId) =>
      (super.noSuchMethod(
            Invocation.method(#getVisitsForPatient, [patientId]),
            returnValue: _i4.Future<List<_i5.Visit>>.value(<_i5.Visit>[]),
          )
          as _i4.Future<List<_i5.Visit>>);

  @override
  _i4.Future<void> insertPayment(_i5.Payment? payment) =>
      (super.noSuchMethod(
            Invocation.method(#insertPayment, [payment]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updatePayment(_i5.Payment? payment) =>
      (super.noSuchMethod(
            Invocation.method(#updatePayment, [payment]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deletePayment(String? paymentId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePayment, [paymentId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.Payment?> getPayment(String? paymentId) =>
      (super.noSuchMethod(
            Invocation.method(#getPayment, [paymentId]),
            returnValue: _i4.Future<_i5.Payment?>.value(),
          )
          as _i4.Future<_i5.Payment?>);

  @override
  _i4.Future<List<_i5.Payment>> getPaymentsForPatient(String? patientId) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentsForPatient, [patientId]),
            returnValue: _i4.Future<List<_i5.Payment>>.value(<_i5.Payment>[]),
          )
          as _i4.Future<List<_i5.Payment>>);
}

/// A class which mocks [GoogleDriveService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleDriveService extends _i1.Mock
    implements _i6.GoogleDriveService {
  MockGoogleDriveService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.AuthenticationState get authenticationState =>
      (super.noSuchMethod(
            Invocation.getter(#authenticationState),
            returnValue: _i6.AuthenticationState.notAuthenticated,
          )
          as _i6.AuthenticationState);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> authenticate({bool? forceAccountSelection = false}) =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, [], {
              #forceAccountSelection: forceAccountSelection,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> refreshTokens() =>
      (super.noSuchMethod(
            Invocation.method(#refreshTokens, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> handleAuthenticationFailure(Exception? error) =>
      (super.noSuchMethod(
            Invocation.method(#handleAuthenticationFailure, [error]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.GoogleSignInAccount>> getAvailableAccounts() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableAccounts, []),
            returnValue: _i4.Future<List<_i7.GoogleSignInAccount>>.value(
              <_i7.GoogleSignInAccount>[],
            ),
          )
          as _i4.Future<List<_i7.GoogleSignInAccount>>);

  @override
  _i4.Future<bool> switchAccount() =>
      (super.noSuchMethod(
            Invocation.method(#switchAccount, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> isAuthenticationValid() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticationValid, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String> getBackupFolderId() =>
      (super.noSuchMethod(
            Invocation.method(#getBackupFolderId, []),
            returnValue: _i4.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#getBackupFolderId, []),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> uploadBackupFile(
    String? fileName,
    List<int>? encryptedData, {
    _i6.ProgressCallback? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadBackupFile,
              [fileName, encryptedData],
              {#onProgress: onProgress},
            ),
            returnValue: _i4.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(
                  #uploadBackupFile,
                  [fileName, encryptedData],
                  {#onProgress: onProgress},
                ),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<List<int>> downloadBackupFile(
    String? fileId, {
    _i6.ProgressCallback? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadBackupFile,
              [fileId],
              {#onProgress: onProgress},
            ),
            returnValue: _i4.Future<List<int>>.value(<int>[]),
          )
          as _i4.Future<List<int>>);

  @override
  _i4.Future<List<_i6.BackupFileInfo>> listBackupFiles() =>
      (super.noSuchMethod(
            Invocation.method(#listBackupFiles, []),
            returnValue: _i4.Future<List<_i6.BackupFileInfo>>.value(
              <_i6.BackupFileInfo>[],
            ),
          )
          as _i4.Future<List<_i6.BackupFileInfo>>);

  @override
  _i4.Future<_i6.BackupFileInfo?> getLatestBackup() =>
      (super.noSuchMethod(
            Invocation.method(#getLatestBackup, []),
            returnValue: _i4.Future<_i6.BackupFileInfo?>.value(),
          )
          as _i4.Future<_i6.BackupFileInfo?>);

  @override
  _i4.Future<void> deleteOldBackups({
    int? maxDailyBackups = 30,
    int? maxMonthlyBackups = 12,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOldBackups, [], {
              #maxDailyBackups: maxDailyBackups,
              #maxMonthlyBackups: maxMonthlyBackups,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> validateBackupIntegrity(
    String? fileId,
    String? expectedChecksum,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#validateBackupIntegrity, [
              fileId,
              expectedChecksum,
            ]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> deleteFile(String? fileId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFile, [fileId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String> updateBackupFile(
    String? fileId,
    String? fileName,
    List<int>? encryptedData, {
    _i6.ProgressCallback? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateBackupFile,
              [fileId, fileName, encryptedData],
              {#onProgress: onProgress},
            ),
            returnValue: _i4.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(
                  #updateBackupFile,
                  [fileId, fileName, encryptedData],
                  {#onProgress: onProgress},
                ),
              ),
            ),
          )
          as _i4.Future<String>);
}

/// A class which mocks [EncryptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEncryptionService extends _i1.Mock implements _i9.EncryptionService {
  MockEncryptionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.EncryptedData> encryptData(
    Map<String, dynamic>? data,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#encryptData, [data, password]),
            returnValue: _i4.Future<_i2.EncryptedData>.value(
              _FakeEncryptedData_0(
                this,
                Invocation.method(#encryptData, [data, password]),
              ),
            ),
          )
          as _i4.Future<_i2.EncryptedData>);

  @override
  _i4.Future<Map<String, dynamic>> decryptData(
    _i2.EncryptedData? encryptedData,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#decryptData, [encryptedData, password]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<String> generateDeviceId() =>
      (super.noSuchMethod(
            Invocation.method(#generateDeviceId, []),
            returnValue: _i4.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#generateDeviceId, []),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> deriveEncryptionKey(
    String? clinicId,
    String? deviceSalt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deriveEncryptionKey, [clinicId, deviceSalt]),
            returnValue: _i4.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#deriveEncryptionKey, [clinicId, deviceSalt]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<bool> validateDataIntegrity(
    List<int>? data,
    String? expectedChecksum,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#validateDataIntegrity, [data, expectedChecksum]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  String generateSalt() =>
      (super.noSuchMethod(
            Invocation.method(#generateSalt, []),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#generateSalt, []),
            ),
          )
          as String);

  @override
  _i4.Future<_i2.DeviceInfo> getDeviceInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceInfo, []),
            returnValue: _i4.Future<_i2.DeviceInfo>.value(
              _FakeDeviceInfo_1(this, Invocation.method(#getDeviceInfo, [])),
            ),
          )
          as _i4.Future<_i2.DeviceInfo>);
}
