// Mocks generated by Mockito 5.4.6 from annotations
// in doc_ledger/test/core/cloud/services/backup_file_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:doc_ledger/core/cloud/services/google_drive_service.dart'
    as _i2;
import 'package:google_sign_in/google_sign_in.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GoogleDriveService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleDriveService extends _i1.Mock
    implements _i2.GoogleDriveService {
  MockGoogleDriveService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthenticationState get authenticationState =>
      (super.noSuchMethod(
            Invocation.getter(#authenticationState),
            returnValue: _i2.AuthenticationState.notAuthenticated,
          )
          as _i2.AuthenticationState);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> authenticate({bool? forceAccountSelection = false}) =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, [], {
              #forceAccountSelection: forceAccountSelection,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> refreshTokens() =>
      (super.noSuchMethod(
            Invocation.method(#refreshTokens, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> handleAuthenticationFailure(Exception? error) =>
      (super.noSuchMethod(
            Invocation.method(#handleAuthenticationFailure, [error]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.GoogleSignInAccount>> getAvailableAccounts() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableAccounts, []),
            returnValue: _i3.Future<List<_i4.GoogleSignInAccount>>.value(
              <_i4.GoogleSignInAccount>[],
            ),
          )
          as _i3.Future<List<_i4.GoogleSignInAccount>>);

  @override
  _i3.Future<bool> switchAccount() =>
      (super.noSuchMethod(
            Invocation.method(#switchAccount, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> isAuthenticationValid() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticationValid, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<String> getBackupFolderId() =>
      (super.noSuchMethod(
            Invocation.method(#getBackupFolderId, []),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#getBackupFolderId, []),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> uploadBackupFile(
    String? fileName,
    List<int>? encryptedData, {
    _i2.ProgressCallback? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadBackupFile,
              [fileName, encryptedData],
              {#onProgress: onProgress},
            ),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(
                  #uploadBackupFile,
                  [fileName, encryptedData],
                  {#onProgress: onProgress},
                ),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<List<int>> downloadBackupFile(
    String? fileId, {
    _i2.ProgressCallback? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadBackupFile,
              [fileId],
              {#onProgress: onProgress},
            ),
            returnValue: _i3.Future<List<int>>.value(<int>[]),
          )
          as _i3.Future<List<int>>);

  @override
  _i3.Future<List<_i2.BackupFileInfo>> listBackupFiles() =>
      (super.noSuchMethod(
            Invocation.method(#listBackupFiles, []),
            returnValue: _i3.Future<List<_i2.BackupFileInfo>>.value(
              <_i2.BackupFileInfo>[],
            ),
          )
          as _i3.Future<List<_i2.BackupFileInfo>>);

  @override
  _i3.Future<_i2.BackupFileInfo?> getLatestBackup() =>
      (super.noSuchMethod(
            Invocation.method(#getLatestBackup, []),
            returnValue: _i3.Future<_i2.BackupFileInfo?>.value(),
          )
          as _i3.Future<_i2.BackupFileInfo?>);

  @override
  _i3.Future<void> deleteOldBackups({
    int? maxDailyBackups = 30,
    int? maxMonthlyBackups = 12,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOldBackups, [], {
              #maxDailyBackups: maxDailyBackups,
              #maxMonthlyBackups: maxMonthlyBackups,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> validateBackupIntegrity(
    String? fileId,
    String? expectedChecksum,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#validateBackupIntegrity, [
              fileId,
              expectedChecksum,
            ]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> deleteFile(String? fileId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFile, [fileId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> updateBackupFile(
    String? fileId,
    String? fileName,
    List<int>? encryptedData, {
    _i2.ProgressCallback? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateBackupFile,
              [fileId, fileName, encryptedData],
              {#onProgress: onProgress},
            ),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(
                  #updateBackupFile,
                  [fileId, fileName, encryptedData],
                  {#onProgress: onProgress},
                ),
              ),
            ),
          )
          as _i3.Future<String>);
}
